ports:
  - port: 8080
    onOpen: open-preview
  - port: 9000
    onOpen: open-preview
  - port: 8081
    onOpen: open-preview
  - port: 8082
    onOpen: open-preview

tasks:
  - name: Start Docker Compose
    init: docker-compose up -d
